name: training
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.1.4
  pedantic: ^1.11.1
  velocity_x: ^3.3.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_application_id: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
